#Write SQL queries to perform the following tasks using the Sakila database:
#List the number of films per category.

select name, count(*)
from category
join film_category
on category.category_id = film_category.category_id
join film
on film_category.film_id = film.film_id
group by category.name

#Retrieve the store ID, city, and country for each store.

select store_id, city, country
from store
join address
on store.address_id = address.address_id
join city
on address.city_id = city.city_id
join country
on city.country_id = country.country_id

#Calculate the total revenue generated by each store in dollars.

select store.store_id, sum(payment.amount)
from store
left join customer
on customer.store_id = store.store_id
left join rental
on rental.customer_id = customer.customer_id
left join payment
on rental.rental_id = payment.rental_id
group by store.store_id

#Determine the average running time of films for each category.
select category.name as Category, avg(film.length) as "Average Length for movie in Category"
from category
left join film_category
on category.category_id = film_category.category_id
left join film 
on film_category.film_id = film.film_id
group by category.name


